### ISSUE TITLE
Where can I find the firmware?

### ISSUE THREAD

**Issue by chewiedies** [toniz4/tenax#1]
I have ordered the PCBs and built the first pair, but I can't find the firmware.

**Comment by heyitscassio** [comment]
Forgot to push to my qmk fork, sorry about that. Today I will do that in the morning. Here is 2:00am currently.

But for testing, you can use the same cantor firmware, with some changes to the pin definitions.

**Comment by chewiedies** [comment]
No worries! Thanks for the quick response. I flashed the Cantor firmware already. It works to test out the matrix, even though the rows/cols are different. But split comms didn't work at all with the Cantor .bin file.

**Comment by heyitscassio** [comment]
> No worries! Thanks for the quick response. I flashed the Cantor firmware already. It works to test out the matrix, even though the rows/cols are different. But split comms didn't work at all with the Cantor .bin file.

https://github.com/toniz4/qmk_firmware/

try It out with my fork.
